package sample

import com.arellomobile.mvp.InjectViewState
import com.arellomobile.mvp.MvpPresenter
import com.arellomobile.mvp.MvpView
import com.arellomobile.mvp.viewstate.MvpViewState

interface MainView : MvpView {
    fun showMessage(message: String)
}

@InjectViewState
class MainPresenter : MvpPresenter<MainView>() {
    fun onStart() {
        viewState.showMessage("Hello from moxy-ksp!")
    }

    // `viewState` is exposed as plain `MainView` for convenience calls above; the generated
    // `$$State` behind it also implements `MvpViewState`, which is where attach/detach live.
    @Suppress("UNCHECKED_CAST")
    fun attach(view: MainView) {
        (viewState as MvpViewState<MainView>).attachView(view)
    }
}

class ConsoleMainView : MainView {
    override fun showMessage(message: String) {
        println("View received: $message")
    }
}

fun main() {
    val presenter = MainPresenter()

    // Calling onStart() before any view is attached queues the command (default AddToEndStrategy).
    presenter.onStart()

    // Attaching replays it — proves $$State / $$ViewStateProvider / MoxyReflector, all generated by
    // moxy-ksp (resolved from mavenLocal, a real published artifact), work end to end in one
    // ordinary Gradle module — no cross-classloader isolation like the test harness has.
    presenter.attach(ConsoleMainView())
}
